package modules.chat.server;

import java.net.InetAddress;

import achala.communication.server.Server;
import achala.communication.server._Server;
import achala.communication.utilisateur.Utilisateur;
import achala.communication.utilisateur._Utilisateur;

public class LanceServer {

	public static void main(String[] args) {
		Server.startServer("src/modules/chat/clients/policy");
		
		try
		{
			String ip = InetAddress.getLocalHost().getHostAddress();
			_Utilisateur user = new Utilisateur("Serveur", "Admin");
			_Server srv = Server.getServer(ip);
			
			user.connect(srv);
			
			srv.getSharedZone(user, "AutoGeneratedRoom");
			
//			new Thread(){
//				public void run(){
//					try {
//						while(srv.getShares().size() != 5)
//						{
//							sleep(5000);
//							for(_Shared s : srv.getShares())
//							{
//								System.out.println(s.getZoneName());
//							}
//						}
//					} catch (RemoteException | InterruptedException e) {
//						// TODO Auto-generated catch block
//						e.printStackTrace();
//					}
//				}
//			}.start();
			
		}
		catch(Exception ex)
		{
			ex.printStackTrace();	
		}
	}

}
