package modules.chat.server;

import java.net.InetAddress;

import achala.communication.server.Server;
import achala.communication.server._Server;
import achala.communication.utilisateur.Utilisateur;
import achala.communication.utilisateur._Utilisateur;

public class LanceServer {

	public static void main(String[] args) {
		Server.startServer("src/modules/chat/clients/policy");
		
		try
		{
			String ip = InetAddress.getLocalHost().getHostAddress();
			_Utilisateur user = new Utilisateur("Serveur", "Admin");
			_Server srv = Server.getServer(ip);
			
			user.connect(srv);
			
			// Creation d'une zone de partage par defaut
			srv.getSharedZone(user, "AutoGeneratedRoom");
			
		}
		catch(Exception ex)
		{
			ex.printStackTrace();	
		}
	}

}
